In [2]:
import pandas as pd

Os dados disponíveis são resultados da NHNES (National Health and Nutrition Examination Survey), realizada anualmente nos EUA para avaliar a saúde e nutrição de adultos e crianças

In [3]:
df_adultos = pd.read_csv('data/DEMO_PHQ.csv')

In [4]:
df_adultos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5334 entries, 0 to 5333
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      5334 non-null   int64
 1   DPQ010    4836 non-null   float64
 2   DPQ020    4836 non-null   float64
 3   DPQ030    4836 non-null   float64
 4   DPQ040    4836 non-null   float64
 5   DPQ050    4836 non-null   float64
 6   DPQ060    4836 non-null   float64
 7   DPQ070    4836 non-null   float64
 8   DPQ080    4836 non-null   float64
 9   DPQ090    4836 non-null   float64
 10  RIAGENDR  5334 non-null   int64
 11  RIDAGEYR  5334 non-null   int64
 12  RIDRETH1  5334 non-null   int64
 13  DMDEDUC   5334 non-null   int64
 14  INDFMINC  5287 non-null   float64
dtypes: float64(10), int64(5)
memory usage: 625.2 KB

In [5]:
print(f'Quantidade de linhas: {df_adultos.shape[0]}')
print(f'Quantidade de colunas: {df_adultos.shape[1]}')

Quantidade de linhas: 5334
Quantidade de colunas: 15

In [6]:
df_adultos.RIDAGEYR.describe()

count    5334.000000
mean       45.089989
std        20.145853
min        18.000000
25%        27.000000
50%        43.000000
75%        62.000000
max        85.000000
Name: RIDAGEYR, dtype: float64

In [7]:
df_adultos.head()

,SEQN,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,RIAGENDR,RIDAGEYR,RIDRETH1,DMDEDUC,INDFMINC
0,31130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,85,3,4,4.0
1,31131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,44,4,4,11.0
2,31132,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,70,3,5,11.0
3,31134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,73,3,3,12.0
4,31139,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,2,18,2,3,11.0

In [8]:
df_crianca_adulto = pd.read_csv('data/PAG_HEI.csv')

In [9]:
print(f'Quantidade de linhas: {df_crianca_adulto.shape[0]}')
print(f'Quantidade de colunas: {df_crianca_adulto.shape[1]}')

Quantidade de linhas: 9424
Quantidade de colunas: 17

In [10]:
df_crianca_adulto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9424 entries, 0 to 9423
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SEQN                      9424 non-null   int64
 1   PAG_MINW                  7150 non-null   float64
 2   ADHERENCE                 7150 non-null   float64
 3   HEI2015C1_TOTALVEG        8549 non-null   float64
 4   HEI2015C2_GREEN_AND_BEAN  8549 non-null   float64
 5   HEI2015C3_TOTALFRUIT      8549 non-null   float64
 6   HEI2015C4_WHOLEFRUIT      8549 non-null   float64
 7   HEI2015C5_WHOLEGRAIN      8549 non-null   float64
 8   HEI2015C6_TOTALDAIRY      8549 non-null   float64
 9   HEI2015C7_TOTPROT         8549 non-null   float64
 10  HEI2015C8_SEAPLANT_PROT   8549 non-null   float64
 11  HEI2015C9_FATTYACID       8549 non-null   float64
 12  HEI2015C10_SODIUM         8549 non-null   float64
 13  HEI2015C11_REFINEDGRAIN   8549 non-null   float64
 14  HEI2015C12_SFAT           8549 non-null   float64
 15  HEI2015C13_ADDSUG         8549 non-null   float64
 16  HEI2015_TOTAL_SCORE       8549 non-null   float64
dtypes: float64(16), int64(1)
memory usage: 1.2 MB

In [11]:
df_crianca_adulto

,SEQN,PAG_MINW,ADHERENCE,HEI2015C1_TOTALVEG,HEI2015C2_GREEN_AND_BEAN,HEI2015C3_TOTALFRUIT,HEI2015C4_WHOLEFRUIT,HEI2015C5_WHOLEGRAIN,HEI2015C6_TOTALDAIRY,HEI2015C7_TOTPROT,HEI2015C8_SEAPLANT_PROT,HEI2015C9_FATTYACID,HEI2015C10_SODIUM,HEI2015C11_REFINEDGRAIN,HEI2015C12_SFAT,HEI2015C13_ADDSUG,HEI2015_TOTAL_SCORE
0,31128,NaN,NaN,3.083350,0.000000,3.927008,5.000000,0.000000,5.000000,4.251329,0.000000,2.487572,6.911882,10.000000,0.818029,6.408092,47.887262
1,31129,285.450346,2.0,1.697761,0.000000,3.731602,4.929186,0.527631,3.887809,4.693141,0.928562,3.740758,6.146441,7.274979,8.006457,0.000000,45.564326
2,31130,0.000000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,31131,264.711316,2.0,3.115103,0.000000,5.000000,1.320674,0.000000,3.141062,4.071959,2.052399,0.684985,2.297100,9.512964,0.438428,3.919226,35.553899
4,31132,1353.348730,3.0,3.509081,0.000000,5.000000,5.000000,5.000000,4.448512,5.000000,0.000000,2.050769,7.369489,8.887880,8.186877,9.099088,63.551696
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9419,41469,184.711316,2.0,2.555935,0.000000,2.613733,0.000000,0.000000,2.151846,5.000000,0.000000,9.344947,3.535211,4.326307,5.269780,8.195564,42.993323
9420,41471,951.478060,3.0,2.674192,3.769401,2.198817,0.517369,0.463168,4.662005,5.000000,1.191796,6.145146,3.189620,3.766149,3.974279,7.758940,45.310883
9421,41472,27.713626,1.0,2.457422,2.930799,2.311917,0.000000,0.933303,5.000000,5.000000,5.000000,2.090534,8.409844,8.936854,3.063795,0.000000,46.134467
9422,41473,685.912240,3.0,3.907340,5.000000,0.000000,0.000000,0.000000,5.000000,5.000000,5.000000,0.000000,7.458058,10.000000,1.676912,2.751168,45.793478
9423,41474,0.000000,1.0,1.238646,4.610515,0.688137,0.240848,5.000000,5.000000,4.304982,5.000000,2.162293,7.018993,10.000000,7.541082,0.000000,52.805494

### Dicionário - DEMO_PHQ

<b>SEQN</b> - Identificador único do respondente

<b>DPQ010</b> - Nas últimas 2 semanas, com que frequência você ficou incomodado por algum dos problemas a seguir:

Pouco interesse ou pouco prazer em fazer as coisas <br>
**** Serve para todos os DPQ0 **** <br>
0 = Nenhuma vez <br>
1 = Menos de uma semana <br>
2 = Uma semana ou mais <br>
3 = Quase todos os dias <br>
7 = Se recusou a responder <br>
9 = Não sabe <br>

<b>DPQ020</b> - Nas últimas 2 semanas, com que frequência você ficou incomodado por algum dos problemas a seguir:

Se sentiu para baixo, deprimido(a) ou sem perspectiva

<b>DPQ030</b> - Nas últimas 2 semanas, com que frequência você ficou incomodado por algum dos 
problemas a seguir:

Dificuldade para pegar no sono ou permanecer dormindo ou dormiu mais do que o costume

<b>DPQ040</b> - Nas últimas 2 semanas, com que frequência você ficou incomodado por algum dos 
problemas a seguir:

Se sentiu cansado(a) ou com pouca energia

<b>DPQ050</b> - Nas últimas 2 semanas, com que frequência você ficou incomodado por algum dos 
problemas a seguir:

Falta de apetite ou comeu demais

<b>DPQ060</b> - Nas últimas 2 semanas, com que frequência você ficou incomodado por algum dos 
problemas a seguir:

Se sentiu mal consigo mesmo(a) ou achou que é um fracasso ou que decepcionou sua família ou a você mesmo(a)

<b>DPQ070</b> - Nas últimas 2 semanas, com que frequência você ficou incomodado por algum dos 
problemas a seguir:

Dificuldade para se concentrar nas coisas (como ler o jornal ou ver televisão)

<b>DPQ080</b> - Nas últimas 2 semanas, com que frequência você ficou incomodado por algum dos 
problemas a seguir:

Teve lentidão para se movimentar ou falar (a ponto de outras pessoas perceberem), ou ao contrário, esteve tão agitado(a) que você ficava andando de um lado para o outro mais do que costume

<b>DPQ090</b> - Nas últimas 2 semanas, com que frequência você ficou incomodado por algum dos 
problemas a seguir:

Pensou em se ferir de alguma maneira ou que seria melhor estar morto(a)

<b>RIAGENDR</b> - Gênero
1 = Masculino <br>
2 = Feminino

<b>RIDAGEYR</b> Idade em anos

<b>RIDRETH1</b> Raça/Etnia

1 = Branco não-hispânico <br>
2 = Negro não-hispânico <br>
3 = Mexicano-americano <br>
4 = Outro <br>
5 = Outro-Hispânico <br>

<b>DMDEDUC</b> Escolaridade

1 = Menor que 9o ano <br>
2 = 9-12o ano <br>
3 = Ensino médio <br>
4 = Ensino superior incompleto <br>
5 = Superior completo ou maior <br>
7 = Se recusou a responder <br>
9 = Não sabe

<b>INDFMINC</b> Renda anual familiar (US$)

1 = 0-4999 <br> 
2 = 5000-9999 <br>
3 = 10000-14999 <br>
4 = 15000-19999 <br>
5 = 20000-24999 <br>
6 = 25000-34999 <br>
7 = 35000-44999 <br>
8 = 45000-54999 <br>
9 = 55000-64999 <br>
10 = 65000-74999 <br>
11 = Maior ou igual a 75000 <br>
12 = Maior que 20000 <br>
13 = Menor que 20000 <br>
77 = Se recusou a responder <br>
99 = Não sabe

### Dicionário - PAG_HEI

<b>SEQN</b> - Identificador único do respondente

<b>PAG_MINW</b> - Tempo total semanal de atividade aeróbica moderada-vigorosa em minutos segundo o Physical Activity 
Guideline (PAG)

<b>ADHERENCE</b> - Grupo de aderência ao Physical Activity Guideline (PAG)

1 = Baixo (< 150 min/semana) <br>
2 = Adequado (150-300 min/semana) <br>
3 = Acima (> 300 min/semana) <br>

<b>HEI2015C1_TOTALVEG</b> Healthy Eating Index - Componente 1 - Total de Vegetais 0-5

<b>HEI2015C2_GREEN_AND_BEAN</b> Healthy Eating Index - Componente 2 - Verduras verde-escuras e leguminosas 0-5

<b>HEI2015C3_TOTALFRUIT</b> Healthy Eating Index - Componente 3 - Frutas totais 0-5

<b>HEI2015C4_WHOLEFRUIT</b> Healthy Eating Index - Componente 4 - Frutas in natura 0-5

<b>HEI2015C5_WHOLEGRAIN</b> Healthy Eating Index - Componente 5 - Grãos integrais 0-10

<b>HEI2015C6_TOTALDAIRY</b> Healthy Eating Index - Componente 6 - Laticínios 0-10

<b>HEI2015C7_TOTPROT</b> Healthy Eating Index - Componente 7 - Proteínas 0-5

<b>HEI2015C8_SEAPLANT_PROT</b> Healthy Eating Index - Componente 8 - Plantas marinhas e proteínas vegetais 0-5

<b>HEI2015C9_FATTYACID</b> Healthy Eating Index - Componente 9 - Ácido-graxo 0-10

<b>HEI2015C10_SODIUM</b> Healthy Eating Index - Componente 10 - Sódio 0-10

<b>HEI2015C11_REFINEDGRAIN</b> Healthy Eating Index - Componente 11 - Grãos refinados 0-10

<b>HEI2015C12_SFAT</b> Healthy Eating Index - Componente 12 - Gordura saturada 0-10

<b>HEI2015C13_ADDSUG</b> Healthy Eating Index - Componente 13 - Açúcares adicionados 0-10

<b>HEI2015_TOTAL_SCORE</b> Healthy Eating Index - Escore total 0-100

In [12]:
#### Juntando os dataset's em um com apenas os adultos
df = pd.merge(df_adultos, df_crianca_adulto, how = 'left', on = 'SEQN')

In [13]:
df.shape

(5334, 31)

In [14]:
df

,SEQN,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,...,HEI2015C5_WHOLEGRAIN,HEI2015C6_TOTALDAIRY,HEI2015C7_TOTPROT,HEI2015C8_SEAPLANT_PROT,HEI2015C9_FATTYACID,HEI2015C10_SODIUM,HEI2015C11_REFINEDGRAIN,HEI2015C12_SFAT,HEI2015C13_ADDSUG,HEI2015_TOTAL_SCORE
0,31130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,31131,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,3.141062,4.071959,2.052399,0.684985,2.297100,9.512964,0.438428,3.919226,35.553899
2,31132,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.000000,4.448512,5.000000,0.000000,2.050769,7.369489,8.887880,8.186877,9.099088,63.551696
3,31134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.217331,2.313900,5.000000,1.268648,2.958985,0.000000,5.627488,5.863078,5.878686,42.886826
4,31139,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,...,0.211544,0.000000,4.088849,4.221442,10.000000,2.845774,0.000000,10.000000,9.658507,47.074393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5329,41466,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,4.607930,2.555736,5.000000,4.672204,4.633477,0.000000,6.580006,8.393244,9.360990,59.949915
5330,41468,0.0,2.0,0.0,1.0,1.0,2.0,1.0,3.0,0.0,...,3.041603,5.000000,3.759596,2.344264,4.780282,3.134216,1.986137,5.850269,10.000000,57.747869
5331,41469,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,2.151846,5.000000,0.000000,9.344947,3.535211,4.326307,5.269780,8.195564,42.993323
5332,41472,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.933303,5.000000,5.000000,5.000000,2.090534,8.409844,8.936854,3.063795,0.000000,46.134467
5333,41473,0.0,0.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.000000,5.000000,5.000000,5.000000,0.000000,7.458058,10.000000,1.676912,2.751168,45.793478

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5334 entries, 0 to 5333
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SEQN                      5334 non-null   int64
 1   DPQ010                    4836 non-null   float64
 2   DPQ020                    4836 non-null   float64
 3   DPQ030                    4836 non-null   float64
 4   DPQ040                    4836 non-null   float64
 5   DPQ050                    4836 non-null   float64
 6   DPQ060                    4836 non-null   float64
 7   DPQ070                    4836 non-null   float64
 8   DPQ080                    4836 non-null   float64
 9   DPQ090                    4836 non-null   float64
 10  RIAGENDR                  5334 non-null   int64
 11  RIDAGEYR                  5334 non-null   int64
 12  RIDRETH1                  5334 non-null   int64
 13  DMDEDUC                   5334 non-null   int64
 14  INDFMINC                  5287 non-null   float64
 15  PAG_MINW                  5334 non-null   float64
 16  ADHERENCE                 5334 non-null   float64
 17  HEI2015C1_TOTALVEG        5060 non-null   float64
 18  HEI2015C2_GREEN_AND_BEAN  5060 non-null   float64
 19  HEI2015C3_TOTALFRUIT      5060 non-null   float64
 20  HEI2015C4_WHOLEFRUIT      5060 non-null   float64
 21  HEI2015C5_WHOLEGRAIN      5060 non-null   float64
 22  HEI2015C6_TOTALDAIRY      5060 non-null   float64
 23  HEI2015C7_TOTPROT         5060 non-null   float64
 24  HEI2015C8_SEAPLANT_PROT   5060 non-null   float64
 25  HEI2015C9_FATTYACID       5060 non-null   float64
 26  HEI2015C10_SODIUM         5060 non-null   float64
 27  HEI2015C11_REFINEDGRAIN   5060 non-null   float64
 28  HEI2015C12_SFAT           5060 non-null   float64
 29  HEI2015C13_ADDSUG         5060 non-null   float64
 30  HEI2015_TOTAL_SCORE       5060 non-null   float64
dtypes: float64(26), int64(5)
memory usage: 1.3 MB

In [16]:
df = df.drop('SEQN', 1)

/tmp/ipykernel_12264/2139918723.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop('SEQN', 1)

In [17]:
df

,DPQ010,DPQ020,DPQ030,DPQ040,DPQ050,DPQ060,DPQ070,DPQ080,DPQ090,RIAGENDR,...,HEI2015C5_WHOLEGRAIN,HEI2015C6_TOTALDAIRY,HEI2015C7_TOTPROT,HEI2015C8_SEAPLANT_PROT,HEI2015C9_FATTYACID,HEI2015C10_SODIUM,HEI2015C11_REFINEDGRAIN,HEI2015C12_SFAT,HEI2015C13_ADDSUG,HEI2015_TOTAL_SCORE
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,...,0.000000,3.141062,4.071959,2.052399,0.684985,2.297100,9.512964,0.438428,3.919226,35.553899
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,...,5.000000,4.448512,5.000000,0.000000,2.050769,7.369489,8.887880,8.186877,9.099088,63.551696
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,...,2.217331,2.313900,5.000000,1.268648,2.958985,0.000000,5.627488,5.863078,5.878686,42.886826
4,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,2,...,0.211544,0.000000,4.088849,4.221442,10.000000,2.845774,0.000000,10.000000,9.658507,47.074393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5329,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2,...,4.607930,2.555736,5.000000,4.672204,4.633477,0.000000,6.580006,8.393244,9.360990,59.949915
5330,0.0,2.0,0.0,1.0,1.0,2.0,1.0,3.0,0.0,2,...,3.041603,5.000000,3.759596,2.344264,4.780282,3.134216,1.986137,5.850269,10.000000,57.747869
5331,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,...,0.000000,2.151846,5.000000,0.000000,9.344947,3.535211,4.326307,5.269780,8.195564,42.993323
5332,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,...,0.933303,5.000000,5.000000,5.000000,2.090534,8.409844,8.936854,3.063795,0.000000,46.134467
5333,0.0,0.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,1,...,0.000000,5.000000,5.000000,5.000000,0.000000,7.458058,10.000000,1.676912,2.751168,45.793478

In [18]:
#### Renomeando as colunas
df = df.rename(columns={'DPQ010': 'Q1',
                        'DPQ020': 'Q2',
                        'DPQ030': 'Q3',
                        'DPQ040': 'Q4',
                        'DPQ050': 'Q5',
                        'DPQ060': 'Q6',
                        'DPQ070': 'Q7',
                        'DPQ080': 'Q8',
                        'DPQ090': 'Q9',
                        'RIAGENDR': 'genero',
                        'RIDAGEYR': 'idade',
                        'RIDRETH1': 'raca',
                        'DMDEDUC': 'escolaridade',
                        'INDFMINC': 'renda_anual_familiar',
                        'PAG_MINW': 'tempo_atividade_semanal_pag',
                        'ADHERENCE': 'aderencia_pag',
                        'HEI2015C1_TOTALVEG': 'total_vegetais',
                        'HEI2015C2_GREEN_AND_BEAN': 'total_verdura-v-escura-leguminosas',
                        'HEI2015C3_TOTALFRUIT': 'total_frutas',
                        'HEI2015C4_WHOLEFRUIT': 'total_frutas_in-natura',
                        'HEI2015C5_WHOLEGRAIN': 'total_graos-integrais',
                        'HEI2015C6_TOTALDAIRY': 'total_laticinios',
                        'HEI2015C7_TOTPROT': 'total_proteinas',
                        'HEI2015C8_SEAPLANT_PROT': 'total_planta-marinha-proteina-vegetal',
                        'HEI2015C9_FATTYACID': 'total_acido-graxo',
                        'HEI2015C10_SODIUM': 'total_sodio',
                        'HEI2015C11_REFINEDGRAIN': 'total_graos-refinados',
                        'HEI2015C12_SFAT': 'total_gordura-saturada',
                        'HEI2015C13_ADDSUG': 'total_acucar-adicionado',
                        'HEI2015_TOTAL_SCORE': 'score_saude'})

#### Renomeando registros (Linhas)

In [19]:
df.genero = df.genero.replace({1: 'homem', 2: 'mulher'})

In [20]:
df.raca = df.raca.replace({1: 'Branco nao-hispanico', 
                           2: 'Negro nao-hispanico ',
                           3: 'Mexicano-americano',
                           4: 'Outro',
                           5: 'Outro-Hispanico '})

In [21]:
df.escolaridade = df.escolaridade.replace({1: 'Menor que 9o ano', 
                                           2: '9-12o ano', 
                                           3: 'Ensino medio', 
                                           4:'Ensino superior incompleto', 
                                           5:'Superior completo ou maior', 
                                           7: 'Se recusou a responder',
                                           9: 'Nao sabe'})

In [22]:
df.aderencia_pag = df.aderencia_pag.replace({1.0: 'Baixo (< 150 min/semana)', 
                                             2.0: 'Adequado (150-300 min/semana)', 
                                             3.0: 'Acima (> 300 min/semana)'})

In [23]:
### criando o csv com os dados tratados
df.to_csv('data/dados_tratados.csv', index=False)